### ISSUE TITLE
Initial Project Roadmap

### ISSUE THREAD

**Issue by EiffL** [GalSim-developers/JAX-GalSim#3]
This issue is to discuss the various aspects of the roadmap necessary to reach a minimal implementation following the guidelines of the [design document ](https://docs.google.com/document/d/1NalCc_5dc3Z8F4q37y-RsJS_mr9gzvfyANb2PYUpsb4/edit?usp=sharing) and reaching our initial target of replicating [`demo1.py`](https://github.com/GalSim-developers/GalSim/blob/releases/2.3/examples/demo1.py).

Feel free to comment below if you see important missing steps.

# Feature implementation

Adding necessary objects:
- [x] #6
- [x] #11
- [x] #12
- [x] #15
- [x] #16 
- [x] [`InterpolatedImage`](https://github.com/GalSim-developers/GalSim/blob/ece3bd32c1ae6ed771f2b489c5ab1b25729e0ea4/galsim/interpolatedimage.py#L35)
- [x] #18
- [x] #19
- [x] [`GaussianNoise`](https://github.com/GalSim-developers/GalSim/blob/ece3bd32c1ae6ed771f2b489c5ab1b25729e0ea4/galsim/noise.py#L224)

Adding core functionalities:
- [x] Implement xValue kValue functions for Gaussian and Exponential light profiles
- [x] Implement `drawImage` and `drawkImage` for Gaussian and Exponential light profiles
- [x] Implement Fourier convolution

# Infrastructure

- [x] #8 
- [x] #13
- [x] Setup CI system using GitHub actions  
- [ ] #17

**Comment by ismael-mendoza** [comment]
Release #87 subsumes this, in any case only the documentation is missing
